# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: camera_id.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'camera_id.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61mera_id.proto\x12\x04ltpb*\x8a\x01\n\x08\x43\x61meraID\x12\x06\n\x02\x41\x31\x10\x00\x12\x06\n\x02\x41\x32\x10\x01\x12\x06\n\x02\x41\x33\x10\x02\x12\x06\n\x02\x41\x34\x10\x03\x12\x06\n\x02\x41\x35\x10\x04\x12\x06\n\x02\x42\x31\x10\x05\x12\x06\n\x02\x42\x32\x10\x06\x12\x06\n\x02\x42\x33\x10\x07\x12\x06\n\x02\x42\x34\x10\x08\x12\x06\n\x02\x42\x35\x10\t\x12\x06\n\x02\x43\x31\x10\n\x12\x06\n\x02\x43\x32\x10\x0b\x12\x06\n\x02\x43\x33\x10\x0c\x12\x06\n\x02\x43\x34\x10\r\x12\x06\n\x02\x43\x35\x10\x0e\x12\x06\n\x02\x43\x36\x10\x0f')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_id_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERAID']._serialized_start=26
  _globals['_CAMERAID']._serialized_end=164
# @@protoc_insertion_point(module_scope)
