# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: color_calibration.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'color_calibration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import matrix3x3f_pb2 as matrix3x3f__pb2
import point3f_pb2 as point3f__pb2
import point2f_pb2 as point2f__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63olor_calibration.proto\x12\x04ltpb\x1a\x10matrix3x3f.proto\x1a\rpoint3f.proto\x1a\rpoint2f.proto\"\xb8\x05\n\x10\x43olorCalibration\x12\x33\n\x04type\x18\x01 \x02(\x0e\x32%.ltpb.ColorCalibration.IlluminantType\x12(\n\x0e\x66orward_matrix\x18\x02 \x02(\x0b\x32\x10.ltpb.Matrix3x3F\x12&\n\x0c\x63olor_matrix\x18\x03 \x02(\x0b\x32\x10.ltpb.Matrix3x3F\x12\x10\n\x08rg_ratio\x18\x04 \x02(\x02\x12\x10\n\x08\x62g_ratio\x18\x05 \x02(\x02\x12#\n\x0cmacbeth_data\x18\x06 \x03(\x0b\x32\r.ltpb.Point3F\x12%\n\x0eilluminant_spd\x18\x07 \x03(\x0b\x32\r.ltpb.Point2F\x12:\n\rspectral_data\x18\x08 \x01(\x0b\x32#.ltpb.ColorCalibration.SpectralData\x1a\xc7\x01\n\x0cSpectralData\x12\x41\n\x06\x66ormat\x18\x01 \x02(\x0e\x32\x31.ltpb.ColorCalibration.SpectralData.ChannelFormat\x12@\n\x0c\x63hannel_data\x18\x02 \x03(\x0b\x32*.ltpb.ColorCalibration.SpectralSensitivity\"2\n\rChannelFormat\x12\x08\n\x04MONO\x10\x00\x12\x07\n\x03RGB\x10\x01\x12\x0e\n\nBAYER_RGGB\x10\x02\x1a\x43\n\x13SpectralSensitivity\x12\r\n\x05start\x18\x01 \x02(\r\x12\x0b\n\x03\x65nd\x18\x02 \x02(\r\x12\x10\n\x04\x64\x61ta\x18\x03 \x03(\x02\x42\x02\x10\x01\"b\n\x0eIlluminantType\x12\x05\n\x01\x41\x10\x00\x12\x07\n\x03\x44\x35\x30\x10\x01\x12\x07\n\x03\x44\x36\x35\x10\x02\x12\x07\n\x03\x44\x37\x35\x10\x03\x12\x06\n\x02\x46\x32\x10\x04\x12\x06\n\x02\x46\x37\x10\x05\x12\x07\n\x03\x46\x31\x31\x10\x06\x12\x08\n\x04TL84\x10\x07\x12\x0b\n\x07UNKNOWN\x10\x63')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'color_calibration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLORCALIBRATION_SPECTRALSENSITIVITY'].fields_by_name['data']._loaded_options = None
  _globals['_COLORCALIBRATION_SPECTRALSENSITIVITY'].fields_by_name['data']._serialized_options = b'\020\001'
  _globals['_COLORCALIBRATION']._serialized_start=82
  _globals['_COLORCALIBRATION']._serialized_end=778
  _globals['_COLORCALIBRATION_SPECTRALDATA']._serialized_start=410
  _globals['_COLORCALIBRATION_SPECTRALDATA']._serialized_end=609
  _globals['_COLORCALIBRATION_SPECTRALDATA_CHANNELFORMAT']._serialized_start=559
  _globals['_COLORCALIBRATION_SPECTRALDATA_CHANNELFORMAT']._serialized_end=609
  _globals['_COLORCALIBRATION_SPECTRALSENSITIVITY']._serialized_start=611
  _globals['_COLORCALIBRATION_SPECTRALSENSITIVITY']._serialized_end=678
  _globals['_COLORCALIBRATION_ILLUMINANTTYPE']._serialized_start=680
  _globals['_COLORCALIBRATION_ILLUMINANTTYPE']._serialized_end=778
# @@protoc_insertion_point(module_scope)
