# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face_data.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'face_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import camera_id_pb2 as camera__id__pb2
import rectanglei_pb2 as rectanglei__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x61\x63\x65_data.proto\x12\x04ltpb\x1a\x0f\x63\x61mera_id.proto\x1a\x10rectanglei.proto\"\xa3\x01\n\x08\x46\x61\x63\x65\x44\x61ta\x12\x1a\n\x02id\x18\x01 \x02(\x0e\x32\x0e.ltpb.CameraID\x12\x13\n\x0b\x66rame_index\x18\x02 \x02(\r\x12 \n\x04rois\x18\x03 \x03(\x0b\x32\x12.ltpb.FaceData.ROI\x1a\x44\n\x03ROI\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1d\n\x03roi\x18\x02 \x01(\x0b\x32\x10.ltpb.RectangleI\x12\x12\n\nconfidence\x18\x03 \x01(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACEDATA']._serialized_start=61
  _globals['_FACEDATA']._serialized_end=224
  _globals['_FACEDATA_ROI']._serialized_start=156
  _globals['_FACEDATA_ROI']._serialized_end=224
# @@protoc_insertion_point(module_scope)
