# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gps_data.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gps_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egps_data.proto\x12\x04ltpb\"\xa4\x06\n\x07GPSData\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x0b\n\x03\x64op\x18\x04 \x01(\x01\x12\"\n\x05track\x18\x05 \x01(\x0b\x32\x13.ltpb.GPSData.Track\x12&\n\x07heading\x18\x06 \x01(\x0b\x32\x15.ltpb.GPSData.Heading\x12(\n\x08\x61ltitude\x18\x07 \x01(\x0b\x32\x16.ltpb.GPSData.Altitude\x12\r\n\x05speed\x18\x08 \x01(\x01\x12\x39\n\x11processing_method\x18\t \x01(\x0e\x32\x1e.ltpb.GPSData.ProcessingMethod\x1a\x41\n\x05Track\x12\r\n\x05value\x18\x01 \x02(\x01\x12)\n\x03ref\x18\x02 \x02(\x0e\x32\x1c.ltpb.GPSData.ReferenceNorth\x1a\x43\n\x07Heading\x12\r\n\x05value\x18\x01 \x02(\x01\x12)\n\x03ref\x18\x02 \x02(\x0e\x32\x1c.ltpb.GPSData.ReferenceNorth\x1aG\n\x08\x41ltitude\x12\r\n\x05value\x18\x01 \x02(\x01\x12,\n\x03ref\x18\x02 \x02(\x0e\x32\x1f.ltpb.GPSData.ReferenceAltitude\"\xc1\x01\n\x10ProcessingMethod\x12\x1d\n\x19PROCESSING_METHOD_UNKNOWN\x10\x00\x12\x19\n\x15PROCESSING_METHOD_GPS\x10\x01\x12\x1c\n\x18PROCESSING_METHOD_CELLID\x10\x02\x12\x1a\n\x16PROCESSING_METHOD_WLAN\x10\x03\x12\x1c\n\x18PROCESSING_METHOD_MANUAL\x10\x04\x12\x1b\n\x17PROCESSING_METHOD_FUSED\x10\x05\"H\n\x0eReferenceNorth\x12\x1c\n\x18REFERENCE_NORTH_MAGNETIC\x10\x00\x12\x18\n\x14REFERENCE_NORTH_TRUE\x10\x01\"5\n\x11ReferenceAltitude\x12 \n\x1cREFERENCE_ALTITUDE_SEA_LEVEL\x10\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gps_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GPSDATA']._serialized_start=25
  _globals['_GPSDATA']._serialized_end=829
  _globals['_GPSDATA_TRACK']._serialized_start=297
  _globals['_GPSDATA_TRACK']._serialized_end=362
  _globals['_GPSDATA_HEADING']._serialized_start=364
  _globals['_GPSDATA_HEADING']._serialized_end=431
  _globals['_GPSDATA_ALTITUDE']._serialized_start=433
  _globals['_GPSDATA_ALTITUDE']._serialized_end=504
  _globals['_GPSDATA_PROCESSINGMETHOD']._serialized_start=507
  _globals['_GPSDATA_PROCESSINGMETHOD']._serialized_end=700
  _globals['_GPSDATA_REFERENCENORTH']._serialized_start=702
  _globals['_GPSDATA_REFERENCENORTH']._serialized_end=774
  _globals['_GPSDATA_REFERENCEALTITUDE']._serialized_start=776
  _globals['_GPSDATA_REFERENCEALTITUDE']._serialized_end=829
# @@protoc_insertion_point(module_scope)
