# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hw_info.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'hw_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sensor_type_pb2 as sensor__type__pb2
import camera_id_pb2 as camera__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhw_info.proto\x12\x04ltpb\x1a\x11sensor_type.proto\x1a\x0f\x63\x61mera_id.proto\"\x9b\x05\n\x12\x43\x61meraModuleHwInfo\x12\x1a\n\x02id\x18\x01 \x02(\x0e\x32\x0e.ltpb.CameraID\x12 \n\x06sensor\x18\x02 \x02(\x0e\x32\x10.ltpb.SensorType\x12=\n\x04lens\x18\x03 \x01(\x0e\x32!.ltpb.CameraModuleHwInfo.LensType:\x0cLENS_UNKNOWN\x12]\n\x0fmirror_actuator\x18\x04 \x01(\x0e\x32+.ltpb.CameraModuleHwInfo.MirrorActuatorType:\x17MIRROR_ACTUATOR_UNKNOWN\x12\x43\n\x06mirror\x18\x05 \x01(\x0e\x32#.ltpb.CameraModuleHwInfo.MirrorType:\x0eMIRROR_UNKNOWN\"a\n\x08LensType\x12\x10\n\x0cLENS_UNKNOWN\x10\x00\x12\x0f\n\x0bLENS_SHOWIN\x10\x01\x12\x0f\n\x0bLENS_LARGAN\x10\x02\x12\x0e\n\nLENS_SUNNY\x10\x03\x12\x11\n\rLENS_KANTATSU\x10\x04\"J\n\x12MirrorActuatorType\x12\x1b\n\x17MIRROR_ACTUATOR_UNKNOWN\x10\x00\x12\x17\n\x13MIRROR_ACTUATOR_PZT\x10\x01\"U\n\nMirrorType\x12\x12\n\x0eMIRROR_UNKNOWN\x10\x00\x12\x19\n\x15MIRROR_DIELECTRIC_SNX\x10\x01\x12\x18\n\x14MIRROR_SILVER_ZUISHO\x10\x02\"^\n\x10LensActuatorType\x12\x19\n\x15LENS_ACTUATOR_UNKNOWN\x10\x00\x12\x18\n\x14LENS_ACTUATOR_SHICOH\x10\x01\x12\x15\n\x11LENS_ACTUATOR_PZT\x10\x02\"\xfa\x02\n\x06HwInfo\x12(\n\x06\x63\x61mera\x18\x01 \x03(\x0b\x32\x18.ltpb.CameraModuleHwInfo\x12\x34\n\x05\x66lash\x18\x02 \x01(\x0e\x32\x16.ltpb.HwInfo.FlashType:\rFLASH_UNKNOWN\x12.\n\x03tof\x18\x03 \x01(\x0e\x32\x14.ltpb.HwInfo.ToFType:\x0bTOF_UNKNOWN\x12%\n\x05model\x18\x04 \x01(\x0e\x32\x16.ltpb.HwInfo.ModelType\x12\x14\n\x0cmanufacturer\x18\x05 \x01(\t\"6\n\tFlashType\x12\x11\n\rFLASH_UNKNOWN\x10\x00\x12\x16\n\x12\x46LASH_OSRAM_CBLPM1\x10\x01\"2\n\x07ToFType\x12\x0f\n\x0bTOF_UNKNOWN\x10\x00\x12\x16\n\x12TOF_STMICRO_VL53L0\x10\x01\"7\n\tModelType\x12\x0c\n\x08MODEL_P1\x10\x00\x12\x0e\n\nMODEL_P1_1\x10\x01\x12\x0c\n\x08MODEL_P2\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hw_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERAMODULEHWINFO']._serialized_start=60
  _globals['_CAMERAMODULEHWINFO']._serialized_end=727
  _globals['_CAMERAMODULEHWINFO_LENSTYPE']._serialized_start=371
  _globals['_CAMERAMODULEHWINFO_LENSTYPE']._serialized_end=468
  _globals['_CAMERAMODULEHWINFO_MIRRORACTUATORTYPE']._serialized_start=470
  _globals['_CAMERAMODULEHWINFO_MIRRORACTUATORTYPE']._serialized_end=544
  _globals['_CAMERAMODULEHWINFO_MIRRORTYPE']._serialized_start=546
  _globals['_CAMERAMODULEHWINFO_MIRRORTYPE']._serialized_end=631
  _globals['_CAMERAMODULEHWINFO_LENSACTUATORTYPE']._serialized_start=633
  _globals['_CAMERAMODULEHWINFO_LENSACTUATORTYPE']._serialized_end=727
  _globals['_HWINFO']._serialized_start=730
  _globals['_HWINFO']._serialized_end=1108
  _globals['_HWINFO_FLASHTYPE']._serialized_start=945
  _globals['_HWINFO_FLASHTYPE']._serialized_end=999
  _globals['_HWINFO_TOFTYPE']._serialized_start=1001
  _globals['_HWINFO_TOFTYPE']._serialized_end=1051
  _globals['_HWINFO_MODELTYPE']._serialized_start=1053
  _globals['_HWINFO_MODELTYPE']._serialized_end=1108
# @@protoc_insertion_point(module_scope)
