# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imu_data.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'imu_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import point3f_pb2 as point3f__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eimu_data.proto\x12\x04ltpb\x1a\rpoint3f.proto\"\xac\x01\n\x07IMUData\x12\x13\n\x0b\x66rame_index\x18\x01 \x02(\r\x12+\n\raccelerometer\x18\x02 \x03(\x0b\x32\x14.ltpb.IMUData.Sample\x12\'\n\tgyroscope\x18\x03 \x03(\x0b\x32\x14.ltpb.IMUData.Sample\x1a\x36\n\x06Sample\x12\x0f\n\x07row_idx\x18\x01 \x02(\r\x12\x1b\n\x04\x64\x61ta\x18\x02 \x02(\x0b\x32\r.ltpb.Point3F')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imu_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMUDATA']._serialized_start=40
  _globals['_IMUDATA']._serialized_end=212
  _globals['_IMUDATA_SAMPLE']._serialized_start=158
  _globals['_IMUDATA_SAMPLE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
