# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mirror_system.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'mirror_system.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import matrix3x3f_pb2 as matrix3x3f__pb2
import point3f_pb2 as point3f__pb2
import range2f_pb2 as range2f__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13mirror_system.proto\x12\x04ltpb\x1a\x10matrix3x3f.proto\x1a\rpoint3f.proto\x1a\rrange2f.proto\"\x94\x03\n\x0cMirrorSystem\x12+\n\x14real_camera_location\x18\x01 \x02(\x0b\x32\r.ltpb.Point3F\x12\x31\n\x17real_camera_orientation\x18\x02 \x02(\x0b\x32\x10.ltpb.Matrix3x3F\x12$\n\rrotation_axis\x18\x03 \x02(\x0b\x32\r.ltpb.Point3F\x12-\n\x16point_on_rotation_axis\x18\x04 \x02(\x0b\x32\r.ltpb.Point3F\x12\x37\n/distance_mirror_plane_to_point_on_rotation_axis\x18\x05 \x02(\x02\x12\x34\n\x1dmirror_normal_at_zero_degrees\x18\x06 \x02(\x0b\x32\r.ltpb.Point3F\x12\x19\n\x11\x66lip_img_around_x\x18\x07 \x02(\x08\x12)\n\x12mirror_angle_range\x18\x08 \x02(\x0b\x32\r.ltpb.Range2F\x12\x1a\n\x12reprojection_error\x18\t \x01(\x02\"\xe6\x05\n\x15MirrorActuatorMapping\x12K\n\x13transformation_type\x18\x01 \x02(\x0e\x32..ltpb.MirrorActuatorMapping.TransformationType\x12\x1e\n\x16\x61\x63tuator_length_offset\x18\x02 \x02(\x02\x12\x1d\n\x15\x61\x63tuator_length_scale\x18\x03 \x02(\x02\x12\x1b\n\x13mirror_angle_offset\x18\x04 \x02(\x02\x12\x1a\n\x12mirror_angle_scale\x18\x05 \x02(\x02\x12N\n\x17\x61\x63tuator_angle_pair_vec\x18\x06 \x03(\x0b\x32-.ltpb.MirrorActuatorMapping.ActuatorAnglePair\x12\x43\n\x0fquadratic_model\x18\x07 \x02(\x0b\x32*.ltpb.MirrorActuatorMapping.QuadraticModel\x12 \n\x18\x61ngle_to_hall_code_error\x18\x08 \x01(\x02\x12 \n\x18hall_code_to_angle_error\x18\t \x01(\x02\x12&\n\x0fhall_code_range\x18\n \x01(\x0b\x32\r.ltpb.Range2F\x1a\x35\n\x11\x41\x63tuatorAnglePair\x12\x11\n\thall_code\x18\x01 \x02(\x05\x12\r\n\x05\x61ngle\x18\x02 \x02(\x02\x1a\x8d\x01\n\x0eQuadraticModel\x12\"\n\x1ause_rplus_for_left_segment\x18\x01 \x02(\x08\x12#\n\x1buse_rplus_for_right_segment\x18\x02 \x02(\x08\x12\x18\n\x10inflection_value\x18\x03 \x02(\x02\x12\x18\n\x0cmodel_coeffs\x18\x04 \x03(\x02\x42\x02\x10\x01\"@\n\x12TransformationType\x12\x16\n\x12MEAN_STD_NORMALIZE\x10\x00\x12\x12\n\x0eTAN_HALF_THETA\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mirror_system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MIRRORACTUATORMAPPING_QUADRATICMODEL'].fields_by_name['model_coeffs']._loaded_options = None
  _globals['_MIRRORACTUATORMAPPING_QUADRATICMODEL'].fields_by_name['model_coeffs']._serialized_options = b'\020\001'
  _globals['_MIRRORSYSTEM']._serialized_start=78
  _globals['_MIRRORSYSTEM']._serialized_end=482
  _globals['_MIRRORACTUATORMAPPING']._serialized_start=485
  _globals['_MIRRORACTUATORMAPPING']._serialized_end=1227
  _globals['_MIRRORACTUATORMAPPING_ACTUATORANGLEPAIR']._serialized_start=964
  _globals['_MIRRORACTUATORMAPPING_ACTUATORANGLEPAIR']._serialized_end=1017
  _globals['_MIRRORACTUATORMAPPING_QUADRATICMODEL']._serialized_start=1020
  _globals['_MIRRORACTUATORMAPPING_QUADRATICMODEL']._serialized_end=1161
  _globals['_MIRRORACTUATORMAPPING_TRANSFORMATIONTYPE']._serialized_start=1163
  _globals['_MIRRORACTUATORMAPPING_TRANSFORMATIONTYPE']._serialized_end=1227
# @@protoc_insertion_point(module_scope)
