# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proximity_sensors.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proximity_sensors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proximity_sensors.proto\x12\x04ltpb\"l\n\x10ProximitySensors\x12\x10\n\x08sensor_1\x18\x01 \x02(\x08\x12\x10\n\x08sensor_2\x18\x02 \x02(\x08\x12\x10\n\x08sensor_3\x18\x03 \x02(\x08\x12\x10\n\x08sensor_4\x18\x04 \x02(\x08\x12\x10\n\x08sensor_5\x18\x05 \x02(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proximity_sensors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROXIMITYSENSORS']._serialized_start=33
  _globals['_PROXIMITYSENSORS']._serialized_end=141
# @@protoc_insertion_point(module_scope)
