# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_type.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sensor_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sensor_type.proto\x12\x04ltpb*\x88\x01\n\nSensorType\x12\x12\n\x0eSENSOR_UNKNOWN\x10\x00\x12\x10\n\x0cSENSOR_AR835\x10\x01\x12\x11\n\rSENSOR_AR1335\x10\x02\x12\x16\n\x12SENSOR_AR1335_MONO\x10\x03\x12\x11\n\rSENSOR_IMX386\x10\x04\x12\x16\n\x12SENSOR_IMX386_MONO\x10\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORTYPE']._serialized_start=28
  _globals['_SENSORTYPE']._serialized_end=164
# @@protoc_insertion_point(module_scope)
