# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vignetting_characterization.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'vignetting_characterization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import matrix4x4f_pb2 as matrix4x4f__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!vignetting_characterization.proto\x12\x04ltpb\x1a\x10matrix4x4f.proto\"\x81\x04\n\x1aVignettingCharacterization\x12\x42\n\tcrosstalk\x18\x01 \x02(\x0b\x32/.ltpb.VignettingCharacterization.CrosstalkModel\x12J\n\nvignetting\x18\x02 \x03(\x0b\x32\x36.ltpb.VignettingCharacterization.MirrorVignettingModel\x12\x1b\n\x13relative_brightness\x18\x03 \x01(\x02\x12\x16\n\x0elens_hall_code\x18\x04 \x01(\x05\x1ah\n\x0e\x43rosstalkModel\x12\r\n\x05width\x18\x01 \x02(\r\x12\x0e\n\x06height\x18\x02 \x02(\r\x12\x1e\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x10.ltpb.Matrix4x4F\x12\x17\n\x0b\x64\x61ta_packed\x18\x04 \x03(\x02\x42\x02\x10\x01\x1ap\n\x15MirrorVignettingModel\x12\x11\n\thall_code\x18\x01 \x02(\x05\x12\x44\n\nvignetting\x18\x02 \x02(\x0b\x32\x30.ltpb.VignettingCharacterization.VignettingModel\x1a\x42\n\x0fVignettingModel\x12\r\n\x05width\x18\x01 \x02(\r\x12\x0e\n\x06height\x18\x02 \x02(\r\x12\x10\n\x04\x64\x61ta\x18\x03 \x03(\x02\x42\x02\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vignetting_characterization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIGNETTINGCHARACTERIZATION_CROSSTALKMODEL'].fields_by_name['data_packed']._loaded_options = None
  _globals['_VIGNETTINGCHARACTERIZATION_CROSSTALKMODEL'].fields_by_name['data_packed']._serialized_options = b'\020\001'
  _globals['_VIGNETTINGCHARACTERIZATION_VIGNETTINGMODEL'].fields_by_name['data']._loaded_options = None
  _globals['_VIGNETTINGCHARACTERIZATION_VIGNETTINGMODEL'].fields_by_name['data']._serialized_options = b'\020\001'
  _globals['_VIGNETTINGCHARACTERIZATION']._serialized_start=62
  _globals['_VIGNETTINGCHARACTERIZATION']._serialized_end=575
  _globals['_VIGNETTINGCHARACTERIZATION_CROSSTALKMODEL']._serialized_start=289
  _globals['_VIGNETTINGCHARACTERIZATION_CROSSTALKMODEL']._serialized_end=393
  _globals['_VIGNETTINGCHARACTERIZATION_MIRRORVIGNETTINGMODEL']._serialized_start=395
  _globals['_VIGNETTINGCHARACTERIZATION_MIRRORVIGNETTINGMODEL']._serialized_end=507
  _globals['_VIGNETTINGCHARACTERIZATION_VIGNETTINGMODEL']._serialized_start=509
  _globals['_VIGNETTINGCHARACTERIZATION_VIGNETTINGMODEL']._serialized_end=575
# @@protoc_insertion_point(module_scope)
