# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: distortion.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'distortion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import point2f_pb2 as point2f__pb2
import rectanglei_pb2 as rectanglei__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64istortion.proto\x12\x04ltpb\x1a\rpoint2f.proto\x1a\x10rectanglei.proto\"\xad\x04\n\nDistortion\x12/\n\npolynomial\x18\x01 \x01(\x0b\x32\x1b.ltpb.Distortion.Polynomial\x12!\n\x03\x63ra\x18\x02 \x01(\x0b\x32\x14.ltpb.Distortion.CRA\x1a\xa7\x01\n\nPolynomial\x12(\n\x11\x64istortion_center\x18\x01 \x02(\x0b\x32\r.ltpb.Point2F\x12$\n\rnormalization\x18\x02 \x02(\x0b\x32\r.ltpb.Point2F\x12\x12\n\x06\x63oeffs\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x10\n\x08\x66it_cost\x18\x04 \x01(\x02\x12#\n\tvalid_roi\x18\x05 \x01(\x0b\x32\x10.ltpb.RectangleI\x1a\xa0\x02\n\x03\x43RA\x12(\n\x11\x64istortion_center\x18\x01 \x02(\x0b\x32\r.ltpb.Point2F\x12\x17\n\x0fsensor_distance\x18\x02 \x02(\x02\x12\x1b\n\x13\x65xit_pupil_distance\x18\x03 \x02(\x02\x12\x12\n\npixel_size\x18\x04 \x02(\x02\x12\x1a\n\x03\x63ra\x18\x05 \x03(\x0b\x32\r.ltpb.Point2F\x12\x1d\n\x06\x63oeffs\x18\x06 \x03(\x0b\x32\r.ltpb.Point2F\x12\x10\n\x08\x66it_cost\x18\x07 \x01(\x02\x12#\n\tvalid_roi\x18\x08 \x01(\x0b\x32\x10.ltpb.RectangleI\x12\x16\n\x0elens_hall_code\x18\t \x01(\x02\x12\x1b\n\x13\x64istance_hall_ratio\x18\n \x01(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'distortion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISTORTION_POLYNOMIAL'].fields_by_name['coeffs']._loaded_options = None
  _globals['_DISTORTION_POLYNOMIAL'].fields_by_name['coeffs']._serialized_options = b'\020\001'
  _globals['_DISTORTION']._serialized_start=60
  _globals['_DISTORTION']._serialized_end=617
  _globals['_DISTORTION_POLYNOMIAL']._serialized_start=159
  _globals['_DISTORTION_POLYNOMIAL']._serialized_end=326
  _globals['_DISTORTION_CRA']._serialized_start=329
  _globals['_DISTORTION_CRA']._serialized_end=617
# @@protoc_insertion_point(module_scope)
