# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flash_calibration.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'flash_calibration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66lash_calibration.proto\x12\x04ltpb\"\x9e\x01\n\x10\x46lashCalibration\x12\x13\n\x0bledcool_lux\x18\x01 \x02(\x02\x12\x1a\n\x12ledcool_max_lumens\x18\x02 \x02(\x02\x12\x13\n\x0bledcool_cct\x18\x03 \x02(\x02\x12\x13\n\x0bledwarm_lux\x18\x04 \x02(\x02\x12\x1a\n\x12ledwarm_max_lumens\x18\x05 \x02(\x02\x12\x13\n\x0bledwarm_cct\x18\x06 \x02(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flash_calibration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLASHCALIBRATION']._serialized_start=34
  _globals['_FLASHCALIBRATION']._serialized_end=192
# @@protoc_insertion_point(module_scope)
