# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hot_pixel_map.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'hot_pixel_map.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13hot_pixel_map.proto\x12\x04ltpb\"\xf5\x01\n\x0bHotPixelMap\x12\x33\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32%.ltpb.HotPixelMap.HotPixelMeasurement\x1a\xb0\x01\n\x13HotPixelMeasurement\x12\x13\n\x0b\x64\x61ta_offset\x18\x01 \x02(\x04\x12\x11\n\tdata_size\x18\x02 \x02(\r\x12\x15\n\rdata_exposure\x18\x03 \x02(\r\x12\x1a\n\x12sensor_temparature\x18\x04 \x02(\x05\x12\x13\n\x0bsensor_gain\x18\x05 \x02(\x02\x12\x16\n\x0epixel_variance\x18\x06 \x01(\x02\x12\x11\n\tthreshold\x18\x07 \x01(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hot_pixel_map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOTPIXELMAP']._serialized_start=30
  _globals['_HOTPIXELMAP']._serialized_end=275
  _globals['_HOTPIXELMAP_HOTPIXELMEASUREMENT']._serialized_start=99
  _globals['_HOTPIXELMAP_HOTPIXELMEASUREMENT']._serialized_end=275
# @@protoc_insertion_point(module_scope)
