# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matrix3x3f.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'matrix3x3f.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10matrix3x3f.proto\x12\x04ltpb\"\x81\x01\n\nMatrix3x3F\x12\x0b\n\x03x00\x18\x01 \x02(\x02\x12\x0b\n\x03x01\x18\x02 \x02(\x02\x12\x0b\n\x03x02\x18\x03 \x02(\x02\x12\x0b\n\x03x10\x18\x04 \x02(\x02\x12\x0b\n\x03x11\x18\x05 \x02(\x02\x12\x0b\n\x03x12\x18\x06 \x02(\x02\x12\x0b\n\x03x20\x18\x07 \x02(\x02\x12\x0b\n\x03x21\x18\x08 \x02(\x02\x12\x0b\n\x03x22\x18\t \x02(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matrix3x3f_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATRIX3X3F']._serialized_start=27
  _globals['_MATRIX3X3F']._serialized_end=156
# @@protoc_insertion_point(module_scope)
