# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_characterization.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sensor_characterization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsensor_characterization.proto\x12\x04ltpb\"\x8e\x04\n\x16SensorCharacterization\x12\x13\n\x0b\x62lack_level\x18\x01 \x02(\x02\x12\x13\n\x0bwhite_level\x18\x02 \x02(\x02\x12\x13\n\x0b\x63liff_slope\x18\x03 \x01(\x02\x12=\n\tvst_model\x18\x04 \x03(\x0b\x32*.ltpb.SensorCharacterization.VstNoiseModel\x1a\xf5\x02\n\rVstNoiseModel\x12\x0c\n\x04gain\x18\x01 \x02(\r\x12\x11\n\tthreshold\x18\x02 \x02(\x02\x12\r\n\x05scale\x18\x03 \x02(\x02\x12@\n\x03red\x18\x04 \x02(\x0b\x32\x33.ltpb.SensorCharacterization.VstNoiseModel.VstModel\x12\x42\n\x05green\x18\x05 \x02(\x0b\x32\x33.ltpb.SensorCharacterization.VstNoiseModel.VstModel\x12\x41\n\x04\x62lue\x18\x06 \x02(\x0b\x32\x33.ltpb.SensorCharacterization.VstNoiseModel.VstModel\x12I\n\x0cpanchromatic\x18\x07 \x01(\x0b\x32\x33.ltpb.SensorCharacterization.VstNoiseModel.VstModel\x1a \n\x08VstModel\x12\t\n\x01\x61\x18\x01 \x02(\x02\x12\t\n\x01\x62\x18\x02 \x02(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_characterization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORCHARACTERIZATION']._serialized_start=40
  _globals['_SENSORCHARACTERIZATION']._serialized_end=566
  _globals['_SENSORCHARACTERIZATION_VSTNOISEMODEL']._serialized_start=193
  _globals['_SENSORCHARACTERIZATION_VSTNOISEMODEL']._serialized_end=566
  _globals['_SENSORCHARACTERIZATION_VSTNOISEMODEL_VSTMODEL']._serialized_start=534
  _globals['_SENSORCHARACTERIZATION_VSTNOISEMODEL_VSTMODEL']._serialized_end=566
# @@protoc_insertion_point(module_scope)
