name: "Build and publish"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install Python 
        run: uv python install
      - name: Local install
        run: |
          uv venv
          uv pip install -e .
      - name: Check package runs
        run: uv run mizukage --help
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}